name: Android CI

on:
  push:
    tags:
      - 'v0.0.1'   # Sadece 'v1.0.0' gibi etiketler gönderince çalışır

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Release APK
        uses: gogoadl/github-action-release-apk@v1.0.0-alpha09
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Aşağıdaki bilgiler GitHub > Settings > Secrets and variables kısmına eklenmelidir
          base64-keystore: ${{ secrets.APP_KEYSTORE_BASE64 }}
          keystore-password: ${{ secrets.APP_KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.APP_KEYSTORE_ALIAS }}
          key-password: ${{ secrets.APP_KEY_PASSWORD }}
